
# My fuzzel config ^^

font 		= Lato 
icons-enabled 	= no
prompt 		= "> "

width = 20
lines = 20

line-height = 19

vertical-pad   = 20
horizontal-pad = 40

[border]
	width  = 2
	radius = 1

[colors]
	background	= 24273af1
	text		= cad3f5ff
	prompt 		= b8c0e0ff
	placeholder 	= 8087a2ff
	input 		= cad3f5ff
	match 		= b7bdf8ff
	selection 	= 5b6078ff
	selection-text 	= cad3f5ff
	selection-match = b7bdf8ff
	counter 	= 8087a2ff
	border 		= b7bdf8ff
